name: Lint and Format Check

on:
  push:
    branches:
      - main # Or your main development branch
  pull_request:
    branches:
      - main # Or your main development branch

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Check code formatting with Prettier
        run: bun x prettier --check .
